/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/chapter1': RouteRecordInfo<'/chapter1', '/chapter1', Record<never, never>, Record<never, never>>,
    '/chapter2': RouteRecordInfo<'/chapter2', '/chapter2', Record<never, never>, Record<never, never>>,
    '/chapter3': RouteRecordInfo<'/chapter3', '/chapter3', Record<never, never>, Record<never, never>>,
    '/chapter4': RouteRecordInfo<'/chapter4', '/chapter4', Record<never, never>, Record<never, never>>,
  }
}
